ALTER TABLE ebdb.NTTY_CITY_STATE (
	ADD CREATE_BY BINARY(16) NOT NULL,
	ADD MODIFY_BY BINARY(16) NOT NULL,
	ADD FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	ADD FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);

UPDATE ebdb.NTTY_CITY_STATE SET
CREATE_BY = (SELECT a.ID FROM ebdb.USR_USER a, ebdb.NTTY_EMAIL b WHERE b.EMAIL = 'spencer.bennett@gmail.com' AND a.EMAIL_ID = b.ID),
MODIFY_BY = (SELECT a.ID FROM ebdb.USR_USER a, ebdb.NTTY_EMAIL b WHERE b.EMAIL = 'spencer.bennett@gmail.com' AND a.EMAIL_ID = b.ID);