DROP TABLE IF EXISTS ebdb.NTTY_CITY_STATE;
CREATE TABLE ebdb.NTTY_CITY_STATE (
	ID BINARY(16) NOT NULL UNIQUE,
	CITY VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	STATE VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (CITY, STATE),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);