DROP TABLE IF EXISTS ebdb.NTTY_LOCATION;
CREATE TABLE ebdb.NTTY_LOCATION (
	ID BINARY(16) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	ADDRESS_1 VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	ADDRESS_2 VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	CITY_STATE_ID BINARY(16) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (DESCRIPTION, ADDRESS_1, ADDRESS_2, CITY_STATE_ID),
	FOREIGN KEY (CITY_STATE_ID) REFERENCES ebdb.CITY_STATE(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);