DROP TABLE IF EXISTS ebdb.NTTY_NAME;
CREATE TABLE ebdb.NTTY_NAME (
	ID BINARY(16) NOT NULL UNIQUE,
	LINE_1 VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	LINE_2 VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	LINE_3 VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	NICK VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	PREFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	SUFFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (COMPLETE, LAST, FIRST, MIDDLE, NICK),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTTY_LOCATION(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);