DROP TABLE IF EXISTS ebdb.NTTY_PERSON;
CREATE TABLE ebdb.NTTY_PERSON (
	ID BINARY(16) NOT NULL UNIQUE,
	BIRTH_DATE BIGINT(13) UNSIGNED NOT NULL,
	GENDER VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_ID BINARY(16) NOT NULL,
	LOCATION_ID BINARY(16) NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID),
	FOREIGN KEY (NAME_ID) REFERENCES ebdb.NTTY_NAME(ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTTY_LOCATION(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);