DROP TABLE IF EXISTS ebdb.NTTY_EMAIL;
CREATE TABLE ebdb.NTTY_EMAIL (
	ID BINARY(16) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PRIMARY KEY (EMAIL)
);

INSERT INTO ebdb.NTTY_EMAIL 
(ID, EMAIL) 
VALUES (
UNHEX(REPLACE(uuid(),'-','')),
'spencer.bennett@gmail.com'
);