INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Saint Paul', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Maplewood', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Oakdale', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Hastings', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Farmington', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('South Saint Paul', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('West Saint Paul', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Inver Grove Heights', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('North Oaks', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Hudson', 'WI');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Mahtomedi', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('North Saint Paul', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Minneapolis', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Woodbury', 'MN');

INSERT INTO ebdb.NTT_CITY_STATE (CITY, STATE) 
VALUES ('Mendota Heights', 'MN');
