DROP TABLE IF EXISTS ebdb.NTT_LOCATION;
CREATE TABLE ebdb.NTT_LOCATION (
	ID BINARY(16) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	ADDRESS_1 VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	ADDRESS_2 VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	CITY_STATE_ID BINARY(16) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (DESCRIPTION, ADDRESS_1, ADDRESS_2, CITY_STATE_ID),
	FOREIGN KEY (CITY_STATE_ID) REFERENCES ebdb.NTT_CITY_STATE(ID)
);