INSERT INTO ebdb.NTT_LOCATION (DESCRIPTION, CITY_STATE_ID) 
VALUES ('LOAD TEST',
(SELECT DISTINCT a.ID FROM ebdb.NTT_CITY_STATE a LIMIT 1));

INSERT INTO ebdb.NTT_LOCATION (DESCRIPTION, CITY_STATE_ID) 
VALUES ('Saint Catherine University',
(SELECT DISTINCT a.ID FROM ebdb.NTT_CITY_STATE a LIMIT 1));

INSERT INTO ebdb.NTT_LOCATION (DESCRIPTION, CITY_STATE_ID) 
VALUES ('Skyview Community School',
(SELECT DISTINCT a.ID FROM ebdb.NTT_CITY_STATE a LIMIT 1));

INSERT INTO ebdb.NTT_LOCATION (DESCRIPTION, CITY_STATE_ID) 
VALUES ('Hamline University',
(SELECT DISTINCT a.ID FROM ebdb.NTT_CITY_STATE a LIMIT 1));
