DROP TABLE IF EXISTS ebdb.NTT_NAME;
CREATE TABLE ebdb.NTT_NAME (
	ID BINARY(16) NOT NULL UNIQUE,
	FIRST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	SECOND VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	THIRD VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	NICK VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	PREFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	SUFFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (FIRST, SECOND, THIRD, NICK)
);