ALTER TABLE ebdb.NTT_NAME (
	ADD COLUMN CREATE_BY BINARY(16) NOT NULL,
	ADD COLUMN MODIFY_BY BINARY(16) NOT NULL
);

ALTER TABLE ebdb.NTT_NAME (
	ADD CONSTRAINT FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	ADD CONSTRAINT FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);

UPDATE ebdb.NTT_NAME SET
CREATE_BY = (SELECT a.ID FROM ebdb.USR_USER a, ebdb.NTT_EMAIL b WHERE b.EMAIL = 'spencer.bennett@gmail.com' AND a.EMAIL_ID = b.ID),
MODIFY_BY = (SELECT a.ID FROM ebdb.USR_USER a, ebdb.NTT_EMAIL b WHERE b.EMAIL = 'spencer.bennett@gmail.com' AND a.EMAIL_ID = b.ID);