DROP TABLE IF EXISTS ebdb.NTT_NAME;
CREATE TABLE ebdb.NTT_NAME (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	FIRST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	MIDDLE VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	LAST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	NICKNAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	PREFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	SUFFIX VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (FIRST, MIDDLE, LAST)
);