INSERT INTO ebdb.NTT_PERSON (BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
'1968-03-23', 'M',
(SELECT DISTINCT a.ID FROM ebdb.NTT_NAME a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a LIMIT 1));

INSERT INTO ebdb.NTT_PERSON (BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
'2005-03-30', 'F',
(SELECT DISTINCT a.ID FROM ebdb.NTT_NAME a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a LIMIT 1));