DROP TABLE IF EXISTS ebdb.NTT_PERSON;
CREATE TABLE ebdb.NTT_PERSON (
	ID BINARY(16) NOT NULL UNIQUE,
	BIRTH_DATE BIGINT(13) UNSIGNED NOT NULL,
	GENDER VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_ID BINARY(16) NOT NULL,
	LOCATION_ID BINARY(16) NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID),
	FOREIGN KEY (NAME_ID) REFERENCES ebdb.NTT_NAME(ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTT_LOCATION(ID)
);