DROP TABLE IF EXISTS ebdb.NTT_PERSON;
CREATE TABLE ebdb.NTT_PERSON (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	BIRTH_DATE DATE NOT NULL,
	GENDER VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_ID INT UNSIGNED NOT NULL,
	LOCATION_ID INT UNSIGNED NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID),
	FOREIGN KEY (NAME_ID) REFERENCES ebdb.NTT_NAME(ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTT_LOCATION(ID)
);