INSERT INTO ebdb.NTT_PERSON (ID, BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
UNHEX(REPLACE(uuid(),'-','')), (UNIX_TIMESTAMP('2005-10-30')*1000), 'F',
(SELECT ID FROM ebdb.NTT_NAME a WHERE a.FIRST = 'Adeline'),
(SELECT ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION = 'LOAD TEST'));

INSERT INTO ebdb.NTT_PERSON (ID, BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
UNHEX(REPLACE(uuid(),'-','')), (UNIX_TIMESTAMP('1968-10-30')*1000), 'M',
(SELECT ID FROM ebdb.NTT_NAME a WHERE a.FIRST = 'Spencer'),
(SELECT ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION = 'LOAD TEST'));