INSERT INTO ebdb.NTT_PERSON (ID, BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
UNHEX(REPLACE(uuid(),'-','')), (UNIX_TIMESTAMP('2005-10-30')*1000), 'F',
(SELECT DISTINCT a.ID FROM ebdb.NTT_NAME a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a LIMIT 1));

INSERT INTO ebdb.NTT_PERSON (ID, BIRTH_DATE, GENDER, NAME_ID, LOCATION_ID) VALUES (
UNHEX(REPLACE(uuid(),'-','')), (UNIX_TIMESTAMP('1968-10-30')*1000), 'M',
(SELECT DISTINCT a.ID FROM ebdb.NTT_NAME a LIMIT 1 OFFSET 1),
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a LIMIT 1));