DROP TABLE IF EXISTS ebdb.NTT_EMAIL;
CREATE TABLE ebdb.NTT_EMAIL (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	EMAIL VARCHAR(255) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (EMAIL)
);