DROP TABLE IF EXISTS ebdb.NTT_EMAIL;
CREATE TABLE ebdb.NTT_EMAIL (
	ID BINARY(16) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (EMAIL)
);