SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ebdb.NTT_PERSON;
DROP TABLE IF EXISTS ebdb.NTT_NAME;
DROP TABLE IF EXISTS ebdb.NTT_LOCATION;
DROP TABLE IF EXISTS ebdb.NTT_CITY_STATE;
DROP TABLE IF EXISTS ebdb.NTT_EMAIL;
SET FOREIGN_KEY_CHECKS = 1;