DROP TABLE IF EXISTS ebdb.OTTR_ATHLETE;
CREATE TABLE ebdb.OTTR_ATHLETE (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	PERSON_ID INT UNSIGNED NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_BY INT UNSIGNED NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	MODIFY_BY INT UNSIGNED NOT NULL,
	PRIMARY KEY (PERSON_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES ebdb.NTT_PERSON(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);