DROP TABLE IF EXISTS ebdb.OTTR_ATHLETE;
CREATE TABLE ebdb.OTTR_ATHLETE (
	ID BINARY(16) NOT NULL,
	BIRTH_DATE DATETIME(3) NOT NULL,
	NAME_LAST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_MIDDLE VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT '',
	NAME_FIRST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	GENDER VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	PRIMARY KEY (ID)
);