DROP TABLE IF EXISTS ebdb.OTTR_ATHLETE;
CREATE TABLE ebdb.OTTR_ATHLETE (
	ID BINARY(16) NOT NULL UNIQUE,
	BIRTH_DATE BIGINT(13) UNSIGNED NOT NULL,
	NAME_LAST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_MIDDLE VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT '',
	NAME_FIRST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	GENDER VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	CREATED_BY VARCHAR
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE IMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY (BIRTH_DATE, NAME_LAST, NAME_FIRST, NAME_MIDDLE, GENDER)
);