DROP TABLE IF EXISTS ebdb.OTTR_TEAM;
CREATE TABLE ebdb.OTTR_TEAM (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NICKNAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '' NOT NULL,
	LOCATION_ID INT UNSIGNED NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_BY INT UNSIGNED NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	MODIFY_BY INT UNSIGNED NOT NULL,
	PRIMARY KEY (NAME, LOCATION_ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTT_LOCATION(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);