DROP TABLE IF EXISTS ebdb.OTTR_TEAM;
CREATE TABLE ebdb.OTTR_TEAM (
	ID BINARY(16) NOT NULL UNIQUE,
	NAME_ID BINARY(16) NOT NULL,
	LOCATION_ID BINARY(16) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (NAME_ID, LOCATION_ID),
	FOREIGN KEY (NAME_ID) REFERENCES ebdb.NTT_NAME(ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES ebdb.NTT_LOCATION(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);