DROP TABLE IF EXISTS ebdb.OTTR_POOL;
CREATE TABLE ebdb.OTTR_POOL (
	ID BINARY(16) NOT NULL,
	NAME VARCHAR(75),
	LOCATION VARCHAR(75),
	CITY VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	STATE VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	PRIMARY KEY (ID)
);