DROP TABLE IF EXISTS ebdb.OTTR_MEET;
CREATE TABLE ebdb.OTTR_MEET (
	ID BINARY(16) NOT NULL,
	MEET_DATE DATETIME(3) NOT NULL,
	DESCRIPTION VARCHAR(75),
	COURSE_TYPE VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	CITY VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	STATE VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	PRIMARY KEY (ID)
);