DROP TABLE IF EXISTS ebdb.OTTR_TEAM;
CREATE TABLE ebdb.OTTR_TEAM (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	YYYY YEAR(4) NOT NULL,
	TEAM_ID BINARY(16) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (YYYY, TEAM_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES ebdb.OTTR_TEAM(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);