DROP TABLE IF EXISTS ebdb.OTTR_EVENT;
CREATE TABLE ebdb.OTTR_EVENT (
	ID BINARY(16) NOT NULL,
	ATHLETE_ID BINARY(16) NOT NULL,
	MEET_ID BINARY(16) NOT NULL,
	STROKE VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	DISTANCE SMALLINT(5) UNSIGNED NOT NULL,
	UNITS VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	IS_RELAY VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT 'N',
	RESULT DATETIME(3) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ATHLETE_ID) REFERENCES ebdb.OTTR_ATHLETE(ID),
	FOREIGN KEY (MEET_ID) REFERENCES ebdb.OTTR_MEET(ID)
);