DROP TABLE IF EXISTS ebdb.OTTR_ROSTER;
CREATE TABLE ebdb.OTTR_ROSTER (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	START_YYYY YEAR(4) NOT NULL,
	END_YYYY YEAR(4) NOT NULL,
	TEAM_ID INT UNSIGNED NOT NULL,
	DESCRIPTION VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' DEFAULT '' NOT NULL,
	START_DATE BIGINT(13) NULL,
	END_DATE BIGINT(13) NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY INT UNSIGNED NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY INT UNSIGNED NOT NULL,
	PRIMARY KEY (START_YYYY, END_YYYY, TEAM_ID, START_DATE, END_DATE),
	FOREIGN KEY (TEAM_ID) REFERENCES ebdb.OTTR_TEAM(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);