INSERT INTO ebdb.OTTR_ROSTER (START_DATE, END_DATE, TEAM_ID, CREATE_BY, MODIFY_BY) VALUES (
(UNIX_TIMESTAMP('2016-01-01')*1000),
(UNIX_TIMESTAMP('2017-12-31')*1000),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'OMNI Otters%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));