INSERT INTO ebdb.OTTR_ROSTER (START_YYYY, END_YYYY, TEAM_ID, CREATE_BY, MODIFY_BY) VALUES (
'2016', '2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'OMNI Otters%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));