DROP TABLE IF EXISTS ebdb.OTTR_MEET;
CREATE TABLE ebdb.OTTR_MEET (
	ID BINARY(16) NOT NULL,
	NAME VARCHAR(75),
	MEET_DATE DATETIME(3) NOT NULL,
	POOL_ID BINARY(16) NOT NULL,
	DESCRIPTION VARCHAR(75),
	COURSE_TYPE VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (POOL_ID) REFERENCES ebdb.OTTR_POOL(ID)
);