DROP TABLE IF EXISTS ebdb.OTTR_TEAM;
CREATE TABLE ebdb.OTTR_TEAM (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	GRADE CHAR(1) DEFAULT '' NOT NULL,
	ATHLETE_ID INT UNSIGNED NOT NULL,
	ROSTER_ID INT UNSIGNED NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_BY INT UNSIGNED NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	MODIFY_BY INT UNSIGNED NOT NULL,
	PRIMARY KEY (GRADE, ATHLETE_ID, ROSTER_ID),
	FOREIGN KEY (ATHLETE_ID) REFERENCES ebdb.OTTR_ATHLETE(ID),
	FOREIGN KEY (ROSTER_ID) REFERENCES ebdb.OTTR_ROSTER(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);