INSERT INTO ebdb.OTTR_ROSTER_ENTRY (GRADE, ATHLETE_ID, ROSTER_ID, CREATE_BY, MODIFY_BY) VALUES (
'SIX',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_ATHLETE a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_ROSTER a, ebdb.OTTR_TEAM b WHERE a.TEAM_ID = b.ID AND b.NAME LIKE 'OMNI Otters%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));