DROP TABLE IF EXISTS ebdb.OTTR_MEET;
CREATE TABLE ebdb.OTTR_MEET (
	ID BINARY(16) NOT NULL,
	NAME_ID BINARY(16) NOT NULL,
	MEET_DATE BIGINT(13) UNSIGNED NOT NULL,
	POOL_ID BINARY(16) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY BINARY(16) NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY BINARY(16) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (NAME_ID) REFERENCES ebdb.NTT_NAME(ID),
	FOREIGN KEY (POOL_ID) REFERENCES ebdb.OTTR_POOL(ID),
	FOREIGN KEY (CREATE_BY) REFERENCES ebdb.USR_USER(ID),
	FOREIGN KEY (MODIFY_BY) REFERENCES ebdb.USR_USER(ID)
);