INSERT INTO ebdb.OTTR_POOL (NAME, LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
'Butler Center',
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Saint Cath%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (NAME, LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
'Bush Center',
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hamline%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hudson Mid%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Levi Dodge%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Central Square%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hastings Middle%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Heritage Middle%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Maplewood Middle%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Veterans%'),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));