INSERT INTO ebdb.OTTR_POOL (NAME, LOCATION_ID) VALUES (
'Butler Center',
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Saint Cath%'));

INSERT INTO ebdb.OTTR_POOL (NAME, LOCATION_ID) VALUES (
'Bush Center',
(SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hamline%'));

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Skyview%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hudson Mid%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Levi Dodge%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Central Square%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hastings Middle%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Heritage Middle%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Maplewood Middle%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Veterans%');

INSERT INTO ebdb.OTTR_POOL (LOCATION_ID) VALUES (
SELECT DISTINCT a.ID FROM ebdb.NTT_LOCATION a WHERE a.DESCRIPTION LIKE 'Hudson Middle%');