INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Summer Skyview Invitational',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Winter Skyview Invitational',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Metro East Conference Dual',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Metro East Conference Junior Varsity Finals',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'IM Tough Challenage',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Minnesota Achievement Championships',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Turkey Trot ABC Open Invite',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Fall Flip Turn',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'June Invite',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Quad Invite',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Turkey Trot',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET_NAME (NAME) VALUES (
'Harvest Moon',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));