INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2016',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Fall Flip%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Hudson%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Hudson Area%'),
(UNIX_TIMESTAMP('2016-10-29')*1000),
(UNIX_TIMESTAMP('2016-10-30')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2016',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Harvest%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Saint Cath%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'North Suburban%'),
(UNIX_TIMESTAMP('2016-11-12')*1000),
(UNIX_TIMESTAMP('2016-11-13')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2016',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Turkey%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Hamline%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'STAR%'),
(UNIX_TIMESTAMP('2016-11-20')*1000),
(UNIX_TIMESTAMP('2016-11-20')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2016',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Quad%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'OMNI%'),
(UNIX_TIMESTAMP('2016-12-09')*1000),
(UNIX_TIMESTAMP('2016-12-09')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Winter%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'OMNI%'),
(UNIX_TIMESTAMP('2017-01-07')*1000),
(UNIX_TIMESTAMP('2017-01-08')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'IM Tough%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Levi Dodge%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Tigersharks%'),
(UNIX_TIMESTAMP('2017-05-20')*1000),
(UNIX_TIMESTAMP('2017-05-21')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'Summer%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'OMNI%'),
(UNIX_TIMESTAMP('2017-06-10')*1000),
(UNIX_TIMESTAMP('2017-06-11')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'June%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Saint Cath%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'South East%'),
(UNIX_TIMESTAMP('2017-06-17')*1000),
(UNIX_TIMESTAMP('2017-06-18')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'MN Achievement%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Saint Cath%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Otters%'),
(UNIX_TIMESTAMP('2017-07-15')*1000),
(UNIX_TIMESTAMP('2017-07-16')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Maplewood%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Hill-Murray%'),
(UNIX_TIMESTAMP('2017-09-07')*1000),
(UNIX_TIMESTAMP('2017-09-07')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE 'White Bear%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Maplewood%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'White Bear%'),
(UNIX_TIMESTAMP('2017-09-09')*1000),
(UNIX_TIMESTAMP('2017-09-09')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Maplewood%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Hill-Murray%'),
(UNIX_TIMESTAMP('2017-09-14')*1000),
(UNIX_TIMESTAMP('2017-09-14')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Heritage%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Simley%'),
(UNIX_TIMESTAMP('2017-09-21')*1000),
(UNIX_TIMESTAMP('2017-09-21')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Hastings Middle%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Hastings%'),
(UNIX_TIMESTAMP('2017-09-28')*1000),
(UNIX_TIMESTAMP('2017-09-28')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Central%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'South Saint%'),
(UNIX_TIMESTAMP('2017-10-05')*1000),
(UNIX_TIMESTAMP('2017-10-05')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Maht%'),
(UNIX_TIMESTAMP('2017-10-12')*1000),
(UNIX_TIMESTAMP('2017-10-12')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Dual'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Skyview%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Tartan%'),
(UNIX_TIMESTAMP('2017-10-17')*1000),
(UNIX_TIMESTAMP('2017-10-17')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_MEET (YYYY, NAME_ID, POOL_ID, HOST_ID, START_DATE, END_DATE, CREATE_BY, MODIFY_BY) VALUES (
'2017',
(SELECT DISTINCT a.ID FROM ebdb.OTTR_MEET_NAME a WHERE a.NAME LIKE '%Junior Varsity%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_POOL a, ebdb.NTT_LOCATION b WHERE a.LOCATION_ID = b.ID AND b.DESCRIPTION LIKE 'Hastings Middle%'),
(SELECT DISTINCT a.ID FROM ebdb.OTTR_TEAM a WHERE a.NAME LIKE 'Hastings%'),
(UNIX_TIMESTAMP('2017-10-26')*1000),
(UNIX_TIMESTAMP('2017-10-26')*1000),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));