INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'A', 'BK', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'B', 'BK', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'C', 'BK', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'A', 'BR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'B', 'BR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'C', 'BR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'A', 'FL', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'B', 'FL', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'C', 'FL', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'A', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'B', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'C', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'E', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'F', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'G', 'FR', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'B', 'IM', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'C', 'IM', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_EVENT (DISTANCE, STROKE, COURSE_TYPE, IS_RELAY, CREATE_BY, MODIFY_BY) VALUES (
'D', 'IM', 'SCY', 'N',
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));