DROP TABLE IF EXISTS ebdb.OTTR_TIME_STANDARD;
CREATE TABLE ebdb.OTTR_TIME_STANDARD (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	EVENT_ID INT UNSIGNED NOT NULL,
	AGE_GROUP CHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	GENDER CHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	STANDARD_KEY CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	STANDARD DECIMAL(6, 2) UNSIGNED NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CREATE_BY INT UNSIGNED NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY_BY INT UNSIGNED NOT NULL,
	PRIMARY KEY (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY),
	FOREIGN KEY (EVENT_ID) REFERENCES ebdb.OTTR_EVENT(ID)
);