/* 50 FREESTYLE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FR'),
'C', 'F', 'A', 29.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FR'),
'C', 'F', 'BB', 31.49,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FR'),
'C', 'F', 'B', 33.79,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FR'),
'C', 'F', 'C', 38.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 100 FREESTYLE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FR'),
'C', 'F', 'A', 63.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FR'),
'C', 'F', 'BB', 68.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FR'),
'C', 'F', 'B', 73.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FR'),
'C', 'F', 'C', 84.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 200 FREESTYLE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FR'),
'C', 'F', 'A', 138.19,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FR'),
'C', 'F', 'BB', 149.69,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FR'),
'C', 'F', 'B', 161.19,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FR'),
'C', 'F', 'C', 185.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 500 FREESTYLE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'E' AND a.STROKE = 'FR'),
'C', 'F', 'A', 367.79,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'E' AND a.STROKE = 'FR'),
'C', 'F', 'BB', 398.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'E' AND a.STROKE = 'FR'),
'C', 'F', 'B', 429.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'E' AND a.STROKE = 'FR'),
'C', 'F', 'C', 493.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 50 BACKSTROKE 11-12 GIRLS */
   
INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BK'),
'C', 'F', 'A', 32.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BK'),
'C', 'F', 'BB', 35.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BK'),
'C', 'F', 'B', 38.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BK'),
'C', 'F', 'C', 44.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 100 BACKSTROKE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BK'),
'C', 'F', 'A', 71.79,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BK'),
'C', 'F', 'BB', 78.49,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BK'),
'C', 'F', 'B', 85.19,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BK'),
'C', 'F', 'C', 97.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 200 BACKSTROKE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BK'),
'C', 'F', 'A', 151.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BK'),
'C', 'F', 'BB', 163.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BK'),
'C', 'F', 'B', 176.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BK'),
'C', 'F', 'C', 202.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 50 BREASTSTROKE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BR'),
'C', 'F', 'A', 36.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BR'),
'C', 'F', 'BB', 39.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BR'),
'C', 'F', 'B', 43.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'BR'),
'C', 'F', 'C', 49.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 100 BREASTSTROKE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BR'),
'C', 'F', 'A', 80.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BR'),
'C', 'F', 'BB', 87.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BR'),
'C', 'F', 'B', 94.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'BR'),
'C', 'F', 'C', 108.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 200 BREASTSTROKE 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BR'),
'C', 'F', 'A', 174.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BR'),
'C', 'F', 'BB', 188.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BR'),
'C', 'F', 'B', 203.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'BR'),
'C', 'F', 'C', 233.49,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 50 BUTTERFLY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FL'),
'C', 'F', 'A', 31.49,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FL'),
'C', 'F', 'BB', 34.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FL'),
'C', 'F', 'B', 36.69,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'A' AND a.STROKE = 'FL'),
'C', 'F', 'C', 42.19,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 100 BUTTERFLY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FL'),
'C', 'F', 'A', 71.49,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FL'),
'C', 'F', 'BB', 78.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FL'),
'C', 'F', 'B', 85.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'FL'),
'C', 'F', 'C', 97.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 200 BUTTERFLY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FL'),
'C', 'F', 'A', 154.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FL'),
'C', 'F', 'BB', 167.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FL'),
'C', 'F', 'B', 180.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'FL'),
'C', 'F', 'C', 207.99,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 100 INDIVIDUAL MEDLEY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'IM'),
'C', 'F', 'A', 72.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'IM'),
'C', 'F', 'BB', 78.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'IM'),
'C', 'F', 'B', 84.39,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'B' AND a.STROKE = 'IM'),
'C', 'F', 'C', 97.09,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 200 INDIVIDUAL MEDLEY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'IM'),
'C', 'F', 'A', 154.89,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'IM'),
'C', 'F', 'BB', 167.79,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'IM'),
'C', 'F', 'B', 180.69,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'C' AND a.STROKE = 'IM'),
'C', 'F', 'C', 207.69,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

/* 400 INDIVIDUAL MEDLEY 11-12 GIRLS */

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'D' AND a.STROKE = 'IM'),
'C', 'F', 'A', 329.29,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'D' AND a.STROKE = 'IM'),
'C', 'F', 'BB', 356.79,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'D' AND a.STROKE = 'IM'),
'C', 'F', 'B', 384.19,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));

INSERT INTO ebdb.OTTR_TIME_STANDARD (EVENT_ID, AGE_GROUP, GENDER, STANDARD_KEY, STANDARD, CREATE_BY, MODIFY_BY) VALUES (
(SELECT DISTINCT a.ID FROM ebdb.OTTR_EVENT a WHERE a.DISTANCE = 'D' AND a.STROKE = 'IM'),
'C', 'F', 'C', 441.59,
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1),
(SELECT DISTINCT a.ID FROM ebdb.USR_USER a LIMIT 1));
