INSERT INTO ebdb.USR_USER (ID, PERSON_ID, EMAIL_ID) VALUES (
UNHEX(REPLACE(uuid(),'-','')),
(SELECT DISTINCT a.ID FROM ebdb.NTT_PERSON a LIMIT 1 OFFSET 1),
(SELECT DISTINCT a.ID FROM ebdb.NTT_EMAIL a LIMIT 1));