DROP TABLE IF EXISTS ebdb.USR_USER;
CREATE TABLE ebdb.USR_USER (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	PERSON_ID INT UNSIGNED NOT NULL UNIQUE,
	EMAIL_ID INT UNSIGNED NOT NULL UNIQUE,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (PERSON_ID) REFERENCES ebdb.NTT_PERSON(ID),
	FOREIGN KEY (EMAIL_ID) REFERENCES ebdb.NTT_EMAIL(ID),
	PRIMARY KEY (PERSON_ID, EMAIL_ID)
);