DROP TABLE IF EXISTS ebdb.USR_USER;
CREATE TABLE ebdb.USR_USER (
	ID BINARY(16) NOT NULL UNIQUE,
	PERSON_ID BINARY(16) NOT NULL UNIQUE,
	EMAIL_ID BINARY(16) NOT NULL UNIQUE,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (PERSON_ID) REFERENCES ebdb.NTTY_PERSON(ID),
	FOREIGN KEY (EMAIL_ID) REFERENCES ebdb.NTTY_EMAIL(ID),
	PRIMARY KEY (EMAIL)
);