DROP TABLE IF EXISTS ebdb.USR_PROFILE;
CREATE TABLE ebdb.USR_PROFILE (
	USER_ID BINARY(16) NOT NULL,
	NAME_LAST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	NAME_MIDDLE VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT '',
	NAME_FIRST VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES ebdb.USR_USER(ID)
);